version: "3.5"
services:
  certbot:
    image: certbot/certbot:latest
    container_name: cmd_certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email miracle3070@naver.com --agree-tos --no-eff-email -d www.share42-together.com
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/logs:/var/log/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw
    networks:
      share42_net:
        ipv4_address: 172.42.0.6

networks:
  share42_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16