version: "3.5"

services:
  jenkins:
    container_name: jenkins-server
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      share42_net:
        ipv4_address: 172.42.0.2
    restart: always

  mariadb:
    container_name: mariadb-server
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .mariadb_env
    environment:
      TZ: Asia/Seoul
    networks:
      share42_net:
        ipv4_address: 172.42.0.3
    restart: always

  redis:
    container_name: redis-server
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      share42_net:
        ipv4_address: 172.42.0.4

  nginx:
    container_name: nginx-server
    image: nginx:1.21.5-alpine   
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      share42_net:
        ipv4_address: 172.42.0.5
    restart: always
  
networks:
  share42_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16