pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the Git repository...'
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Building the Spring Boot project using Gradle...'
                dir('AMAG_Project/Backend') {
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                dir('AMAG_Project/Backend') {
                    script {
                        def dockerImage = docker.build("your-docker-repo/your-image-name:latest")
                    }
                }
            }
        }
        stage('Docker Deploy') {
            steps {
                echo 'Deploying Docker container...'
                script {
                    def dockerImage = docker.image("your-docker-repo/your-image-name:latest")
                    docker.withRegistry('https://registry.hub.docker.com', 'your-credentials') {
                        dockerImage.push()
                    }
                    dockerImage.run('-p 8088:8088 --name your-container-name')
                }
            }
        }
    }
}